# Generated by Django 3.2.9 on 2021-11-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('unique_doctor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('unique_hospital_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('ssn_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorHospitalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorHospitalMembership_withDoctor', to='appointment_booking.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorHospitalMembership_withHospital', to='appointment_booking.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=False)),
                ('doctor_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorAvailability_withDoctorHospital', to='appointment_booking.doctorhospitalmembership')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_withDoctorAvailability', to='appointment_booking.doctoravailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_forPatient', to='appointment_booking.patient')),
            ],
        ),
    ]
