# Generated by Django 3.2.9 on 2021-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='unique_doctor_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='unique_hospital_id',
            field=models.IntegerField(unique=True),
        ),
    ]
